---
- name: Install Nginx on web servers
  hosts: all
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: present
